services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - medireach-network

  ai-service:
    build:
      context: ./AI
    ports:
      - "8000:8000"
    networks:
      - medireach-network

  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:80"
    networks:
      - medireach-network
    depends_on:
      - backend
      - ai-service

networks:
  medireach-network:
    driver: bridge
